### ISSUE TITLE
write a hello world program

### ISSUE THREAD

**Issue by gpalmersheim** [dustintp/hello-world#1]
Let's write a program that takes a file as input and writes out a formatted Welcome Message

in a file called Gary.txt enter "Gary Palmersheim"

in an executable file read the file Gary.txt and write
"Welcome Gary Palmersheim"

**Comment by dustintp** [comment]
any hints on how to write the program?

**Comment by gpalmersheim** [comment]
sure - try a printf statement
  Printf "%s\n" "$(<gary.txt)"

everything inside the ( ) is run as a subshell - so the out put is gary.txt directed to the output stream.  The $ makes it a variable.  The printf takes that string inside the " " and substitutes it for %s and the \n will print a new line

don't forget to make your program executable

**Comment by dustintp** [comment]
done, pls review and commit

**Comment by gpalmersheim** [comment]
closed
